### ISSUE TITLE
Repository status?

### ISSUE THREAD

**Issue by solonovamax** [MinnDevelopment/jda-ktx#10]
What's the status of this repository?

I know that, [per your announcement](https://user-images.githubusercontent.com/46940694/131269565-3c953b60-1e7b-42bb-b2c6-d4399fa066b5.png), you're stepping away from JDA. And taking an extended break.
Does that include this repository as well?

Do you plan to continue supporting this repository and maintaining it with future JDA updates, as well as dealing with bug reports, and adding new features as needed?
If not, I'd be more than happy to take over maintaining this repository for you, given that I'm using it in my bot and I find it very useful.

**Comment by MinnDevelopment** [comment]
This project is nothing official, I simply publish my own utilities that I use in my personal projects here. You can easily use a fork of your own through the same [jitpack method](https://github.com/MinnDevelopment/jda-ktx#download) used to import this library. All you have to do is switch to your own GitHub username instead of mine.

**Comment by solonovamax** [comment]
Mhm, I recognize it's not an "official JDA" repository, I was just wondering if you'd continue maintaining this, or whether I should fork it and continue with that.

I'm currently doing just that with jitpack, for my bot. Though, I do have a group in the maven central repository, I just felt it wouldn't be respectful to publish a lib in there unless I was the maintainer.

I'd just thought that, for the sake of ease-of-use for anyone else who wanted to use this, it'd be nice if there could be one "primary" fork that is sort of actively maintained
